### ISSUE TITLE
Error: The remote "ubuntu-minimal" doesn't exist

### ISSUE THREAD

**Issue by hiyyg** [isolin/mitsuba2lxd#1]
Hi, thanks for the scripts. I got this error when using your script:
```
Error: The remote "ubuntu-minimal" doesn't exist
```
Do you know how to solve this?

**Comment by isolin** [comment]
Hi! This should do the job
```bash
 lxc remote add --protocol simplestreams ubuntu-minimal https://cloud-images.ubuntu.com/minimal/releases/
```

For details see [the official repository](https://cloud-images.ubuntu.com/minimal/releases/bionic/) or [simos' blog](https://blog.simos.info/a-closer-look-at-minimal-ubuntu-for-lxd/). There is also a [tutorial](https://ubuntu.com/tutorials/tutorial-setting-up-lxd-1604#1-overview) for the deb/ppa package which can help you in case of any further trouble (e.g. adding yourself to the `lxd` group).


And as I see right now, I fully forgot to include `lxd init`. I will see if I can intergrate it to the script, or if it will stay in the README.

So once more the steps:
1. create `lxd` group and add yourself
2. `lxd init`
3. `lxc remote add --protocol simplestreams ubuntu-minimal https://cloud-images.ubuntu.com/minimal/releases/`

Then you should be ready to kick off the script!

**Comment by isolin** [comment]
@hiyyg Have you been able to setup `lxd` and continue with the Mitsuba script?

**Comment by hiyyg** [comment]
No, I failed with cuda installation issue using this script. I'm not familiar with lxd so I give up trying. Maybe I will try installing mitsuba2 in the future when I have my system upgraded to newer system.

**Comment by isolin** [comment]
I'm sorry to hear that. What GPU do you have?
